[project]
name = "french-pronunciation"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "montreal-forced-aligner>=3.3.8",
    "pandas>=3.0.0",
    "torch>=2.10.0",
    "transformers>=5.0.0",
]
